# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  base46 = {
    pname = "base46";
    version = "ea004cd1031bc8dd7b5fdefe4da7a95920abc4da";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "base46";
      rev = "ea004cd1031bc8dd7b5fdefe4da7a95920abc4da";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-01-18";
  };
  chaivim = {
    pname = "chaivim";
    version = "affa299e0142594fc74ddae0d6f1304acedb5da3";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "chaivim";
      rev = "affa299e0142594fc74ddae0d6f1304acedb5da3";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-01";
  };
  evergarden = {
    pname = "evergarden";
    version = "f7ef9f853b2cff6137e67a7e1e67cec0f947376e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "evergarden";
      rev = "f7ef9f853b2cff6137e67a7e1e67cec0f947376e";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-09";
  };
  fidget = {
    pname = "fidget";
    version = "c12f8a58ee472ce5983c3a3f3aad0ff6c49a6a83";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "c12f8a58ee472ce5983c3a3f3aad0ff6c49a6a83";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-07";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "7178d1a430dcfff8a4c92d78b9e39e0297a779c0";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "7178d1a430dcfff8a4c92d78b9e39e0297a779c0";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-11";
  };
  incline = {
    pname = "incline";
    version = "16fc9c073e3ea4175b66ad94375df6d73fc114c0";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "incline.nvim";
      rev = "16fc9c073e3ea4175b66ad94375df6d73fc114c0";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-05-16";
  };
  indent = {
    pname = "indent";
    version = "65e20ab94a26d0e14acac5049b8641336819dfc7";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "65e20ab94a26d0e14acac5049b8641336819dfc7";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-06-28";
  };
  keymaps = {
    pname = "keymaps";
    version = "62f10ae89dfcf065035c20ad3cda2c84f36e43ab";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "keymaps.nvim";
      rev = "62f10ae89dfcf065035c20ad3cda2c84f36e43ab";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-03-12";
  };
  "lazy.nvim" = {
    pname = "lazy.nvim";
    version = "1d451b4c2ce957da05e2123ce1a001804fc7ea96";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "1d451b4c2ce957da05e2123ce1a001804fc7ea96";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-11";
  };
  lspconfig = {
    pname = "lspconfig";
    version = "cf97d2485fc3f6d4df1b79a3ea183e24c272215e";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "cf97d2485fc3f6d4df1b79a3ea183e24c272215e";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-03";
  };
  lualine = {
    pname = "lualine";
    version = "6a40b530539d2209f7dc0492f3681c8c126647ad";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "6a40b530539d2209f7dc0492f3681c8c126647ad";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-08";
  };
  luasnip = {
    pname = "luasnip";
    version = "ce0a05ab4e2839e1c48d072c5236cce846a387bc";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "ce0a05ab4e2839e1c48d072c5236cce846a387bc";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-06-28";
  };
  mini = {
    pname = "mini";
    version = "6c873ff81c318119923a424e3aea39000d3a10cf";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.nvim";
      rev = "6c873ff81c318119923a424e3aea39000d3a10cf";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-11";
  };
  null = {
    pname = "null";
    version = "0d1b3fa2ad0b371b94cb4b9a27ba6e5a1a915c91";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "0d1b3fa2ad0b371b94cb4b9a27ba6e5a1a915c91";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-06-28";
  };
  nvim-cmp = {
    pname = "nvim-cmp";
    version = "a110e12d0b58eefcf5b771f533fc2cf3050680ac";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "a110e12d0b58eefcf5b771f533fc2cf3050680ac";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-06-08";
  };
  plenary = {
    pname = "plenary";
    version = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-05-20";
  };
  telescope = {
    pname = "telescope";
    version = "bfcc7d5c6f12209139f175e6123a7b7de6d9c18a";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "bfcc7d5c6f12209139f175e6123a7b7de6d9c18a";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-01";
  };
  telescope_fzf = {
    pname = "telescope_fzf";
    version = "cf48d4dfce44e0b9a2e19a008d6ec6ea6f01a83b";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-fzf-native.nvim";
      rev = "cf48d4dfce44e0b9a2e19a008d6ec6ea6f01a83b";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-02";
  };
  telescope_select = {
    pname = "telescope_select";
    version = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-ui-select.nvim";
      rev = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2023-12-04";
  };
  todo_comments = {
    pname = "todo_comments";
    version = "313b04e5b02d29ab9275c9295ff5e2b73921b0eb";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "313b04e5b02d29ab9275c9295ff5e2b73921b0eb";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-07";
  };
  treesitter = {
    pname = "treesitter";
    version = "465840f8c14126e5193d777bbff94036eb875bd5";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "465840f8c14126e5193d777bbff94036eb875bd5";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-11";
  };
  trouble = {
    pname = "trouble";
    version = "4453fea6bb597830fbd58d2c484612f37b97bd8c";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "4453fea6bb597830fbd58d2c484612f37b97bd8c";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-06";
  };
  whichkey = {
    pname = "whichkey";
    version = "af4ded85542d40e190014c732fa051bdbf88be3d";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "af4ded85542d40e190014c732fa051bdbf88be3d";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-07-06";
  };
  yosu = {
    pname = "yosu";
    version = "553c8c526975c5107efde17950417f3738fbb72d";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "yosu.nvim";
      rev = "553c8c526975c5107efde17950417f3738fbb72d";
      fetchSubmodules = false;
      sha256 = "sha256-/4mExTpyQXzDlfCL2q5YJekG4xIY43yATjtcPPiLBOI=";
    };
    date = "2024-06-17";
  };
}
